import type { Metadata } from "next";
import "./globals.css";
import { englebert } from "@/fonts";
import StateContextProvider from "@/context/StateContext";
import Background from "@/components/layout/background/Background";
import Titlebar from "@/components/layout/titlebar/Titlebar";
import Menu from "@/components/layout/menu/Menu";
import Perspective3d from "@/components/common/perserve_3d/Perspective3d";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StateContextProvider>
        <body className={`${englebert.className}`}>
          <Perspective3d className="h-screen w-screen overflow-hidden bg-black grid place-content-center select-none">
            <Background>
              <Titlebar />
              {children}
              <Menu />
            </Background>
          </Perspective3d>
        </body>
      </StateContextProvider>
    </html>
  );
}
